services:
  postgres:
    container_name: spark_db
    image: postgres:18.3-alpine
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: meow
      POSTGRES_PASSWORD: UwU
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./source_data:/docker-entrypoint-initdb.d
    networks:
      - meowork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meow -d spark_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init-scripts:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=meow
      - CLICKHOUSE_PASSWORD=UwU
    networks:
      - meowork
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user meow --password UwU --query 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark_jobs:/scripts
      - ./jars:/jars
    networks:
      - meowork
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      spark-master:
        condition: service_started
    environment:
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    volumes:
      - ./spark_jobs:/scripts
      - ./jars:/jars
    networks:
      - meowork

  spark-submit:
    image: apache/spark:latest
    container_name: spark-submit
    volumes:
      - ./spark_jobs:/scripts
      - ./jars:/jars
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      spark-master:
        condition: service_started
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo 'Step 1: Snowflake ETL (Postgres)...' &&
        /opt/spark/bin/spark-submit \
          --master $$SPARK_MASTER \
          --jars /jars/postgresql-42.7.10.jar \
          /scripts/snowflake_etl.py &&
 
        echo 'Step 2: ClickHouse Marts Generation...' &&
        /opt/spark/bin/spark-submit \
          --master $$SPARK_MASTER \
          --jars /jars/postgresql-42.7.10.jar,/jars/clickhouse-spark-runtime-4.0_2.13-0.10.0.jar \
          --conf spark.sql.catalog.clickhouse=com.clickhouse.spark.ClickHouseCatalog \
          --conf spark.sql.catalog.clickhouse.host=clickhouse \
          --conf spark.sql.catalog.clickhouse.http_port=8123 \
          --conf spark.sql.catalog.clickhouse.user=meow \
          --conf spark.sql.catalog.clickhouse.password=UwU \
          /scripts/spark_mart_gen.py
    networks:
      - meowork

networks:
  meowork:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data: